In [9]:
import numpy as np

In [2]:
#column vector
c = np.array([1, 2, 3])
print(c.shape)

print(c[0])

(3,)
1


In [3]:
#row vector
r = np.array([ [1,2,3] ])
print(r.shape)

(1, 3)


In [4]:
#obtaining a particular entry
print(r[0,1])   #2 dimensional

2


In [10]:
#creationg a matrix with all zeros
a = np.zeros((2,2))   #0의 default matrix인 2,2 matrix size
print(a)

b = np.ones((2,2))
print(b)

c = np.full((2,2), 7)
print(c)

d = np.random.random((2,2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.69605899 0.70602461]
 [0.44311774 0.70829697]]


In [11]:
#creating matrix
A = np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
B = np.array([[11,22,33,22],[44,55,66,11]])
print(B)

[[11 22 33 22]
 [44 55 66 11]]


In [13]:
#transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
#matrix - matrix multiplication
np.dot(A,B)

array([[ 99, 132, 165,  44],
       [209, 286, 363, 110],
       [319, 440, 561, 176]])

In [18]:
#matrix-matrix multiplication
#size should match
np.dot(B,A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [19]:
#coefficient matrix A and a vector b
A = np.array([[60, 5.5, 1], [65, 5.0, 0], [55, 6.0, 1]])
b = np.array([66, 70, 78])

In [20]:
#identity matrix
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#computing an inverse (역행렬)
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [22]:
#wrong matrix multiplication
A * A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [23]:
#correct matrix multiplication
A.dot(A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#solution of a linear system
x = A_inv.dot(b)
x  #최종 솔루션

array([ -0.43478261,  19.65217391, -16.        ])

In [26]:
#a better way to solve the same linear system
from numpy.linalg import solve
x = solve(A,b)
x  #A의 역함수를 구하지 않고 방정식을 직접적으로 풀어내는 형태의 알고리즘
#A의 역함수를 계산을 위해 직접적으로 구하는 경우는 잘 없음

array([ -0.43478261,  19.65217391, -16.        ])