In [1]:
import numpy as np
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

머신러닝 = 데이터 기반으로 패턴을 학습해 결과를 예측하는 알고리즘

선형대수 통계 패키지 numpy

데이터 처리 패키지 pandas

시각화 패키지 matplot // 단점 보완 seaborn

# 넘파이
머신러닝의 주요 알고리즘은 선령대수와 통계 등에 기반

루프를 사용하지 않고, 대량의 데이터를 빠르게 연산
데이터 핸들링 기능 제공


**np.array()**

인자를 입력받아 ndarray로 변환하는 기능으로 생성된 ndarray배열의 shape변수는 ndarray의 크기, 즉 행과 열의 수를 튜플형태로 갖고 있음

이를 통해 ndarray배열의 차원까지 알 수 있음

In [12]:
array1 = np.array([1,2,3])
print("array1 type", type(array1))
print("array1 shape", array1.shape) #3행 배열
print("ar1 ndim", array1.ndim)      #1차원 배열

array1 type <class 'numpy.ndarray'>
array1 shape (3,)
ar1 ndim 1


In [13]:
array2 = np.array([[1,2,3], [4,5,6]])
print("ar2 type", type(array2))
print("ar2 shape", array2.shape) #2열 3행 배열
print("ar2 ndim", array2.ndim)  # 2차원 배열

ar2 type <class 'numpy.ndarray'>
ar2 shape (2, 3)
ar2 ndim 2


In [14]:
array3 = np.array([[1,2,3]])
print("ar3 type", type(array3))
print("ar3 shape", array3.shape)   #1열 3행 배열
print("ar3 ndim", array3.ndim)     #2차원 배열
print("ar3 len", len(array3))
print("ar3 size", array3.size)

ar3 type <class 'numpy.ndarray'>
ar3 shape (1, 3)
ar3 ndim 2
ar3 len 1
ar3 size 3


len()

행의 수 반환

.size

전체 원소의 개수 반환

2X3 배열의 경우 원소 개수인 6반환

**array1과 array2가 같은 데이터 건수를 가짐에도 1차원 / 2차원으로 나뉘는 이유**

array1의 경우([]) 형태로 1데이터

array3의 경우 ([[]])로 이루어진 1개의 로우 3개의 칼럼으로 이루어진 2차원 데이터

**ndarray의 데이터 타입**

ndarray내의 데이터값으로는 숫자, 불, 문자열 등 모두 가능

숫자의 경우 int형 unsigned int형, float형 모두 제공하며 complex타입도 제공

하지만 한 개의 ndarray내부에 int형과 float형이 같이 있을 수 없다 즉 같은 dtype만이 있을 수 있다

In [18]:
list = [1,2,3]
print(type(list))
array1 = np.array(list)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


list 자료형은 ndarray로 형태를 변환할 수 있다

In [22]:
list = [1, 2, 'test']
array1 = np.array(list)
print(array1, array1.dtype)

list2 = [1, 2, 3.1]
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.1] float64


리스트에 숫자형 값과 문자열 값을 섞어서 array를 만들자 ndarray는 데이터 값이 모두 같아야 하므로 모두 문자열 값으로 변경되었다

array2의 경우 모두 float형으로 변경되었다

**astype()**

ndarray내의 데이터 타입 변경

astype()인자에 원하는 데이터 타입을 문자열로 지정   // 대용량의 데이터의 경우 메모리 사용량을 줄이며 데이터 타입을 변경하는데 사용 가능

In [24]:
array1_int = np.array([1,2,3])
array_float = array1_int.astype('float64')
print(array_float, array_float.dtype)

array2_int = array_float.astype('int32')
print(array2_int, array2_int.dtype)

array2_float = np.array([1.1,2.2,3.3])
array3_int = array2_float.astype('int32')
print(array3_int, array3_int.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**arange, zeros, ones**

특정 크기와 차원을 가진 ndarray를 0, 1로 초기화

arange(), zeros(), ones()로 생성하며 주로 대규모 데이터를 초기화해야할 때 사용

**arange()함수의 경우 파이썬 표준 함수 range()와 유사한 기능을 한다**

array를 range로 표현한 것으로 0부터 함수인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

In [25]:
array_arange = np.arange(10)
print(array_arange)
print(array_arange.dtype, array_arange.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


입력된 인자는 stop값이며, 0~9까지의 값으로 구성된 1차원 ndarray를 생성한다 

stop값만 부옇했지만 range와 유사하게 0부터 start값으로 시작한다 // 0이 아닌 다른 값을 start값으로 부여할 수도 있다

zeros()함수 인자로는 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 반환한다 

ones의 경우 1로 반환한다

함수 인자로 dtype을 정해주지 않으면, default로 float64형의 데이터로 ndarray를 채우게 된다

In [38]:
z_array = np.zeros((3,2), 'int32')
print(z_array)
print(z_array.dtype, z_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [41]:
f_array = np.ones((3,2))
print(f_array)
print(f_array.dtype, f_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 차원과 크기 변경 // reshape()**

reshape()매서드는 ndarray를 특정 차원 및 크기로 변환

변환을 원하는 크기를 함수의 인자로 입력

아래 코드의 경우 0~9까지의 1차원 ndarray를 2러우X5칼럼과 5로우X2칼럼 형태로 2차원 ndarray로 변환

In [2]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(2,5)
print(array2)
array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


지정된 사이즈로 변경이 불가능하면 오류 발생

In [3]:
err = array1.reshape(4,3)
print(err)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [5]:
array1 = np.arange(10)
print('array1 \n', array1)
array2 = array1.reshape(-1,5)
print('array2 \n', array2)
array3 = array1.reshape(5,-1)
print('array3 \n', array3)

array1 
 [0 1 2 3 4 5 6 7 8 9]
array2 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


-1을 인자로 적용 시 해당 인자를 array1과 호환 가능한 ndarray로 변환해준다

하지만 10개의 1차원 데이터를 4개의 칼럼을 가진 (-1,4)로 적용 시 변환이 불가능해 에러가 발생한다

(로우, 칼럼)

In [6]:
err2 = array1.reshape(-1,4)
print(err2)

ValueError: cannot reshape array of size 10 into shape (4)

-1인자 이용 시 (-1,1)을 사용게 되면 원본 ndarray가 어떠한 형태이던 반드시 1 개의 칼럼을 가진 ndarray로 변환이 보장된다

tolist() 메서드를 이용하면 리스트 자료형으러 변환이 가능하다

In [15]:
array1 = np.arange(8)
array2 = array1.reshape((2, 2, 2)) #3차원 데이터
print(array2)
print(array2.tolist())

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [17]:
array1=np.arange(10)
array2 = array1.reshape(-1,5)
print(array2.tolist())

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [19]:
array3 = array1.reshape(-1,1)
array3.tolist()

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]

# ndarray의 데이터 세트 선택하기 - indexing



 - 특정 데이터만 추출

원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
 - 슬라이싱
 
 슬라이싱은 연속된 인덱스 상의 ndarrray를 추출하는 방식으로 ':'기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱 -1 위치에 있는 데이터의 ndarray를 반환한다. 예를 들어 1:5라고 하면 시작 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray를 반환한다
 - 팬시 인덱싱
 
일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다
 - 불린 인덱싱
 
특정 조건에 해당하는지 여부인 True/False값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다

**단일 값 추출**

1개의 데이터값을 선택하기 위해선 ndarray객체에 해당하는 위치의 인덱스 값을 []안에 입력하면 된다.

In [20]:
array1 = np.arange(1, 10)
print('array1: ', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [23]:
print('맨 뒤 값', array1[-1])

맨 뒤 값 9


In [24]:
array1[0] = 3
array1[8] = 33
print(array1)

[ 3  2  3  4  5  6  7  8 33]


다차원의 ndarray에서 단일 값 추출하기

2차원상에서 데이터에 접근하기 위해선 ','로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근하면 된다

In [29]:
array1 = np.arange(1,10)
array2 = array1.reshape(-1,3)
print(array2)

print('row=0, column=2 index 가리키는 값: ', array2[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row=0, column=2 index 가리키는 값:  3


**슬라이싱**

1차원 슬라이싱

':'를 이용하면 연속한 데이터를 슬라이싱해서 추출할 수 있다 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터는 모두 ndarray타입이다

':'사이에 시작 인덱스와 종료 인덱스를 표시하면시작 인덱스에서 종료 인덱스 -1 위치에 있는 데이터의 ndarray를 반환한다

In [33]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [35]:
#시작, 종료 인덱스는 생략이 가능하다
array4 = array1[:4]
print(array4)
array5 = array1[5:]
print(array5)
allarr=array1[:]
print(allarr)

[1 2 3 4]
[6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 ndarray에 슬라이싱으로 데이터 접근하기

','를 이용해 로우와 칼럼 인덱스를 지칭

In [48]:
array1 = np.arange(1,10)
array2 = array1.reshape(3,3)
print(array2)

print('array2[0:2], [0,2]: \n'  ,array2[0:2, 0:2])
print('그 다음 \n',array2[1:,2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2], [0,2]: 
 [[1 2]
 [4 5]]
그 다음 
 [[6]
 [9]]


2차원 ndarray에서 뒤에 오는 인덱스 값을 없애면 1차원 ndarray로 반환된다

3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray로 반환된다

In [51]:
print(array2[0])
print(array2[1])
print(array2[0].shape)
print(array2[1].shape)

[1 2 3]
[4 5 6]
(3,)
(3,)


**팬시 인덱싱**

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식이다

In [62]:
array1 = np.arange(start = 1, stop = 10)
array2 = array1.reshape(3,3)
print(array2)

array3 = array2[[0,1], 2]
print(array3)
print('\n')

array4 = array2[[0,1], 0:2]
print(array4)

array5 = array2[[0,1]]
print(array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]


[[1 2]
 [4 5]]
[[1, 2, 3], [4, 5, 6]]


**불린 인덱싱**

조건 필터링과 검색을 동시에 할 수 있어 자주 사용되는 인덱싱 방식이다

불린 인덱싱을 사용하지 않고 1차원 ndarray(1,2,3,4,5,6,7,8,9)에서 데이터값이 5보다 큰 데이터만 추출하려면 for loop을 통해 if 추출값 > 5로 비교를 돌리며 데이터를 추출해야 한다

불린 인덱스[ ] 내에 조건문을 그대로 입력하면 보다 간단하게 구현할 수 있다

In [64]:
aarray1 = np.arange(1,10)

#[ ] 안에 추출값 > 5 boolean indexing 적용
array3 = array1[array1 > 5]
print(array3)

[6 7 8 9]


In [65]:
array1 > 5

array([False, False, False, False, False,  True,  True,  True,  True])

위와 동일한 boolean ndarray를 만들어 array1[ ]에 그대로 입력하면 동일한 데이터가 반환된다

In [66]:
boolean = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1[boolean]
print(array3)

[6 7 8 9]


In [68]:
index = np.array([5,6,7,8])
array4 = array1[index]   #직접 인덱스 집합을 만드어 대입하는 것도 가능하다
print(array4)

[6 7 8 9]
