## 레이블 인코딩

카테고리피처를 코드형 숫자 값으로 변환, '01', '02'와 같은 코드 값 역시 1,2와 같은 숫자형으로 변환

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['티비', '냉장고', '전자렌지', '컴퓨터', '선풍기', '믹서', '믹서']

lb = LabelEncoder()
lb.fit(items)
label = lb.transform(items)
label

array([5, 0, 3, 4, 2, 1, 1])

In [4]:
print('인코딩 클래스', lb.classes_)

인코딩 클래스 ['냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터' '티비']


In [7]:
print('디코딩 원본값', lb.inverse_transform([5, 0, 3, 4, 2, 1, 1]))

디코딩 원본값 ['티비' '냉장고' '전자렌지' '컴퓨터' '선풍기' '믹서' '믹서']


## 원 핫 인코딩

피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식

In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['티비', '냉장고', '전자렌지', '컴퓨터', '선풍기', '믹서', '믹서']
items = np.array(items).reshape(-1,1)

oh = OneHotEncoder()
oh.fit(items)
oh_label = oh.transform(items)

print(oh_label.toarray())
oh_label.shape

[[0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


(7, 6)

In [25]:
#판다스를 이용한 원 핫 인코딩
import pandas as pd

df = pd.DataFrame({'items' :['티비', '냉장고', '전자렌지', '컴퓨터', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터  items_티비
0          0         0          0           0          0         1
1          1         0          0           0          0         0
2          0         0          0           1          0         0
3          0         0          0           0          1         0
4          0         0          1           0          0         0
5          0         1          0           0          0         0
6          0         1          0           0          0         0

## StandardScaler

In [28]:
from sklearn.datasets import load_iris

iris= load_iris()
data = iris.data
label = iris.target
iris_df = pd.DataFrame(data = iris.data, columns=iris.feature_names)
iris_df

print('feature들의 평균값')
print(iris_df.mean())
print('\nfeature들의 분산값')
print(iris_df.var())

feature들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [33]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(iris_df)
iris_scaled = ss.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns=iris.feature_names)

print('feature들의 평균값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산값')
print(iris_df_scaled.var())

feature들의 평균값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


## MinMaxScaler

In [36]:
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()
mm.fit(iris_df)
iris_scaled = mm.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [46]:
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [47]:
mm = MinMaxScaler()
mm.fit(train_array)
train_scaled = mm.transform(train_array)
test_scaled = mm.transform(test_array)
train_scaled.reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [43]:
test_scaled.reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])